version: '3.7'

services:
  retail_service:
    build: ./retail-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./retail-service/:/app/
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URI=postgresql://retail_db_username:retail_db_password@retail_db/retail_db_dev
    depends_on:
      - retail_db

  retail_db:
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_retail:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=retail_db_username
      - POSTGRES_PASSWORD=retail_db_password
      - POSTGRES_DB=retail_db_dev

volumes:
  postgres_data_retail:
