version: '3.7'

services:
  manufacturing_service:
    build: ./manufacturing-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./manufacturing-service/:/app/
    ports:
      - "8080:8000"  # Expose the service directly on port 8080
    environment:
      - DATABASE_URI=postgresql://manufacturing_db_username:manufacturing_db_password@manufacturing_db/manufacturing_db_dev
    depends_on:
      - manufacturing_db

  manufacturing_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_manufacturing:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manufacturing_db_username
      - POSTGRES_PASSWORD=manufacturing_db_password
      - POSTGRES_DB=manufacturing_db_dev

volumes:
  postgres_data_manufacturing:
