version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
      - MANUFACTURING_SERVICE_HOST_URL=http://manufacturing_service:8000/api/v1/manufacturing/
    depends_on:
      - movie_db

  movie_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev

  cast_service:
    build: ./cast-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./cast-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    depends_on:
      - cast_db

  cast_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev

  manufacturing_service:
    build: ./manufacturing-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./manufacturing-service/:/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URI=postgresql://manufacturing_db_username:manufacturing_db_password@manufacturing_db/manufacturing_db_dev
    depends_on:
      - manufacturing_db

  manufacturing_db:
    image: postgres:16.1-alpine
    volumes:
      - postgres_data_manufacturing:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manufacturing_db_username
      - POSTGRES_PASSWORD=manufacturing_db_password
      - POSTGRES_DB=manufacturing_db_dev


  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service
      - manufacturing_service

volumes:
  postgres_data_movie:
  postgres_data_cast:
  postgres_data_manufacturing:
